Log:
  Level: none # Log level: none, error, warning, info, debug
  AccessPath: # /etc/main/access.Log
  ErrorPath: # /etc/main/error.log
DnsConfigPath: /etc/main/dns.json # Path to dns config
RouteConfigPath: /etc/main/route.json # Path to route config
InboundConfigPath: # /etc/main/custom_inbound.json # Path to custom inbound config
OutboundConfigPath: /etc/main/custom_outbound.json # Path to custom outbound config
ConnetionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 10 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "V2board" # Panel type: SSpanel, V2board
    ApiConfig:
      ApiHost: NODE_API # API address
      ApiKey: NODE_KEY # API key
      NodeID: NODE_ID
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 230 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings
      DeviceLimit: 10 # Local settings will replace remote settings
    ControllerConfig:
      ListenIP: 127.0.0.1 # IP address you want to listen
      UpdatePeriodic: 60 # Time to update the node info, how many sec.
      EnableDNS: true # Use custom DNS config, Please ensure that you set the dns.json well
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, dns
